header_include_path: qorvo_mdek1001_driver/qorvo_mdek1001_driver.hpp
namespace: qorvo_mdek1001_driver
node_class_name: QorvoMDEK1001Driver

params:
  autostart:
    type: bool
    default_value: true
    description: "Start sampling on node startup."
    constraints: "Cannot be changed after node startup."
    read_only: true
    var_name: autostart_

  frame_prefix:
    type: string
    default_value: ""
    description: "Prefix to add to the frame_id of the published messages, including the last trailing slash."
    constraints: "Must be a valid frame prefix."
    read_only: true
    var_name: frame_prefix_

  global_frame:
    type: string
    default_value: "world"
    description: "Name of the global frame."
    constraints: "Must be a valid frame name."
    read_only: true
    var_name: global_frame_

  position_variance:
    type: double_array
    default_value:
      - 0.0
      - 0.0
      - 0.0
    min_value: 0.0
    max_value: 1000000.0
    step: 0.0
    description: "Variance of the position estimate."
    constraints: "Must be a valid array of 3 doubles."
    read_only: false
    validator: validate_position_variance

  serial_port:
    type: string
    default_value: "/dev/ttyACM0"
    description: "Serial port to use for communication."
    constraints: "Must be a valid serial port."
    read_only: true
    var_name: serial_port_

  tag_id:
    type: integer
    default_value: 1
    min_value: 1
    max_value: 1000
    step: 1
    description: "Tag ID to use (set here, not given by the actual tag device)."
    constraints: "Cannot be changed after node startup."
    read_only: true
    var_name: tag_id_

  timeout:
    type: integer
    default_value: 200
    min_value: 1
    max_value: 60000
    step: 1
    description: "Serial port I/O calls timeout [ms]."
    constraints: "Cannot be changed after node startup, must not be too lower than the tag's update period."
    read_only: true
    var_name: timeout_
